# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/tyler/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7479.33/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/tyler/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7479.33/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tyler/Downloads/agora-cleanspeak

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tyler/Downloads/agora-cleanspeak

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/tyler/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7479.33/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/tyler/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.7479.33/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyler/Downloads/agora-cleanspeak/CMakeFiles /home/tyler/Downloads/agora-cleanspeak/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tyler/Downloads/agora-cleanspeak/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AgoraAutoModerator

# Build rule for target.
AgoraAutoModerator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AgoraAutoModerator
.PHONY : AgoraAutoModerator

# fast build rule for target.
AgoraAutoModerator/fast:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/build
.PHONY : AgoraAutoModerator/fast

src/ModeratorHandler.o: src/ModeratorHandler.cpp.o

.PHONY : src/ModeratorHandler.o

# target to build an object file
src/ModeratorHandler.cpp.o:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/ModeratorHandler.cpp.o
.PHONY : src/ModeratorHandler.cpp.o

src/ModeratorHandler.i: src/ModeratorHandler.cpp.i

.PHONY : src/ModeratorHandler.i

# target to preprocess a source file
src/ModeratorHandler.cpp.i:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/ModeratorHandler.cpp.i
.PHONY : src/ModeratorHandler.cpp.i

src/ModeratorHandler.s: src/ModeratorHandler.cpp.s

.PHONY : src/ModeratorHandler.s

# target to generate assembly for a file
src/ModeratorHandler.cpp.s:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/ModeratorHandler.cpp.s
.PHONY : src/ModeratorHandler.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/AgoraAutoModerator.dir/build.make CMakeFiles/AgoraAutoModerator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AgoraAutoModerator"
	@echo "... edit_cache"
	@echo "... src/ModeratorHandler.o"
	@echo "... src/ModeratorHandler.i"
	@echo "... src/ModeratorHandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

